//! End-to-end CLI tests for the Modbus TCP analyzer (F-105-003 / D5 holdout acceptance).
//!
//! Exercises the full `reader → reassembler → dispatcher → ModbusAnalyzer` pipeline
//! against a real pcap fixture (`tests/fixtures/modbus-write.pcap`) generated by
//! `tests/fixtures/mk_modbus_pcap.py`.
//!
//! ## Fixture contents (modbus-write.pcap)
//! 8 packets in a Modbus TCP session on port 502:
//!   - Packet 1-3:  TCP three-way handshake (SYN, SYN-ACK, ACK)
//!   - Packet 4:    Client→Server FC=0x11 Report Server ID (recon → T0888)
//!   - Packet 5:    Server→Client FC=0x11 response (also fires T0888, direction-independent)
//!   - Packet 6:    Client→Server FC=0x10 Write Multiple Registers (write → T1692.001+T0836)
//!   - Packet 7:    Server→Client FC=0x90 Exception response (exception_count++)
//!   - Packet 8:    Client→Server FIN-ACK
//!
//! ## Assertions
//! - JSON `analyzers` array contains a "modbus" entry with non-zero pdu_count and write_count.
//! - JSON `findings` array contains:
//!   - At least one T0888 finding (Modbus recon — Report Server ID FC=0x11)
//!   - At least one T1692.001 + T0836 finding (Modbus Write Multiple Registers FC=0x10)
//! - All finding timestamps are in the year 2024 (not 1970, confirming pcap-relative
//!   timestamp provenance through the full pipeline per BC-2.09.007 / VP-021).
//!
//! Traces to: F-105-003, D5 holdout acceptance, BC-2.09.007, VP-021, BC-2.14.013,
//!            BC-2.14.020, BC-2.14.023.
//!
//! Per DF-TEST-NAMESPACE-001: all tests are wrapped in `mod modbus_e2e`.

#![allow(non_snake_case)]

mod modbus_e2e {
    use assert_cmd::Command;

    // Path to the Modbus TCP fixture (relative to the crate root, as assert_cmd uses).
    const FIXTURE: &str = "tests/fixtures/modbus-write.pcap";

    // ---------------------------------------------------------------------------
    // Helper: parse JSON output from wirerust analyze --modbus --output-format json
    // ---------------------------------------------------------------------------

    fn run_modbus_json() -> serde_json::Value {
        let output = Command::cargo_bin("wirerust")
            .expect("wirerust binary must be built")
            .args(["analyze", "--modbus", "--output-format", "json", FIXTURE])
            .assert()
            .success()
            .get_output()
            .stdout
            .clone();

        let text = String::from_utf8(output).expect("wirerust output must be valid UTF-8");
        serde_json::from_str(&text).unwrap_or_else(|e| {
            panic!(
                "wirerust JSON output failed to parse: {e}\nRaw output (first 500 chars):\n{}",
                &text[..500.min(text.len())]
            )
        })
    }

    // ---------------------------------------------------------------------------
    // BC-2.14.023 / F-105-003: CLI invocation succeeds and produces JSON
    // ---------------------------------------------------------------------------

    /// test_BC_2_14_023_modbus_cli_e2e_succeeds_on_port_502_fixture
    ///
    /// Postcondition: `wirerust analyze --modbus --output-format json <fixture>`
    /// exits zero and emits a valid JSON object containing "summary", "findings",
    /// and "analyzers" top-level keys.
    ///
    /// Traces to: BC-2.14.023 postcondition P4; F-105-003.
    #[test]
    fn test_BC_2_14_023_modbus_cli_e2e_succeeds_on_port_502_fixture() {
        let json = run_modbus_json();
        assert!(
            json.get("summary").is_some(),
            "JSON output must have a 'summary' key"
        );
        assert!(
            json.get("findings").is_some(),
            "JSON output must have a 'findings' key"
        );
        assert!(
            json.get("analyzers").is_some(),
            "JSON output must have an 'analyzers' key"
        );
    }

    // ---------------------------------------------------------------------------
    // BC-2.14.021 / F-105-003: modbus analyzer summary appears in analyzers array
    // ---------------------------------------------------------------------------

    /// test_BC_2_14_021_modbus_summary_in_analyzers_array
    ///
    /// Postcondition: the "analyzers" JSON array contains an entry with
    /// `analyzer_name == "modbus"` that has `pdu_count >= 1` and `write_count >= 1`.
    ///
    /// The fixture carries 4 Modbus ADUs (FC=0x11 x2, FC=0x10 x1, FC=0x90 x1),
    /// so pdu_count must be exactly 4.
    ///
    /// Traces to: BC-2.14.021 postcondition 1; F-105-003.
    #[test]
    fn test_BC_2_14_021_modbus_summary_in_analyzers_array() {
        let json = run_modbus_json();
        let analyzers = json["analyzers"]
            .as_array()
            .expect("'analyzers' must be a JSON array");

        let modbus_summary = analyzers
            .iter()
            .find(|a| a["analyzer_name"].as_str() == Some("modbus"))
            .unwrap_or_else(|| {
                panic!(
                    "No 'modbus' entry found in analyzers array. Got: {:?}",
                    analyzers
                        .iter()
                        .map(|a| &a["analyzer_name"])
                        .collect::<Vec<_>>()
                )
            });

        let detail = &modbus_summary["detail"];

        let pdu_count = detail["pdu_count"]
            .as_u64()
            .expect("detail.pdu_count must be a u64");
        assert!(
            pdu_count >= 1,
            "pdu_count must be >= 1; fixture has 4 Modbus ADUs, got {pdu_count}"
        );

        let write_count = detail["write_count"]
            .as_u64()
            .expect("detail.write_count must be a u64");
        assert!(
            write_count >= 1,
            "write_count must be >= 1; fixture has FC=0x10 Write Multiple Registers, got {write_count}"
        );
    }

    /// test_BC_2_14_021_modbus_summary_pdu_count_equals_four
    ///
    /// The fixture has exactly 4 valid Modbus ADUs past the 3-point gate
    /// (FC=0x11 x2, FC=0x10 x1, FC=0x90 x1). pdu_count must equal 4.
    ///
    /// Traces to: BC-2.14.021; F-105-003 D5 acceptance criterion.
    #[test]
    fn test_BC_2_14_021_modbus_summary_pdu_count_equals_four() {
        let json = run_modbus_json();
        let analyzers = json["analyzers"].as_array().expect("analyzers array");
        let modbus = analyzers
            .iter()
            .find(|a| a["analyzer_name"].as_str() == Some("modbus"))
            .expect("modbus entry in analyzers");

        let pdu_count = modbus["detail"]["pdu_count"].as_u64().expect("pdu_count");
        assert_eq!(
            pdu_count, 4,
            "fixture has exactly 4 Modbus ADUs: FC=0x11(req), FC=0x11(resp), FC=0x10(write), FC=0x90(exc); got {pdu_count}"
        );
    }

    /// test_BC_2_14_021_modbus_summary_exception_count_nonzero
    ///
    /// The fixture contains one FC=0x90 exception response, so exception_count must be 1.
    ///
    /// Traces to: BC-2.14.021; BC-2.14.019 exception detection.
    #[test]
    fn test_BC_2_14_021_modbus_summary_exception_count_nonzero() {
        let json = run_modbus_json();
        let analyzers = json["analyzers"].as_array().expect("analyzers array");
        let modbus = analyzers
            .iter()
            .find(|a| a["analyzer_name"].as_str() == Some("modbus"))
            .expect("modbus entry in analyzers");

        let exc_count = modbus["detail"]["exception_count"]
            .as_u64()
            .expect("exception_count");
        assert_eq!(
            exc_count, 1,
            "fixture has exactly 1 exception response (FC=0x90); got {exc_count}"
        );
    }

    // ---------------------------------------------------------------------------
    // BC-2.14.013 / BC-2.14.020: findings array — T1692.001+T0836 and T0888
    // ---------------------------------------------------------------------------

    /// test_BC_2_14_013_findings_contain_modbus_write_T1692_001_T0836
    ///
    /// Postcondition: at least one finding in the "findings" array contains
    /// both "T1692.001" and "T0836" in its `mitre_techniques` list.
    ///
    /// The fixture's FC=0x10 Write Multiple Registers (a register-write FC)
    /// must emit a write finding with MITRE tags T1692.001 (Unauthorized Message: Command Message) and
    /// T0836 (Modify Control Logic), per BC-2.14.013 / ORCHESTRATOR RULING BC-DISCREPANCY-001.
    ///
    /// Traces to: BC-2.14.013 postcondition invariant 1; F-105-003.
    #[test]
    fn test_BC_2_14_013_findings_contain_modbus_write_T0855_T0836() {
        let json = run_modbus_json();
        let findings = json["findings"]
            .as_array()
            .expect("'findings' must be a JSON array");

        assert!(
            !findings.is_empty(),
            "findings array must not be empty; fixture should produce write and recon findings"
        );

        let has_write_finding = findings.iter().any(|f| {
            if let Some(techniques) = f["mitre_techniques"].as_array() {
                let strs: Vec<&str> = techniques.iter().filter_map(|t| t.as_str()).collect();
                strs.contains(&"T1692.001") && strs.contains(&"T0836")
            } else {
                false
            }
        });

        assert!(
            has_write_finding,
            "No finding with both T1692.001 and T0836 found. FC=0x10 (Write Multiple Registers) must emit T1692.001+T0836. Findings: {:?}",
            findings
                .iter()
                .map(|f| &f["mitre_techniques"])
                .collect::<Vec<_>>()
        );
    }

    /// test_BC_2_14_020_findings_contain_modbus_recon_T0888
    ///
    /// Postcondition: at least one finding contains "T0888" in `mitre_techniques`.
    ///
    /// The fixture's FC=0x11 Report Server ID (packets 4 and 5) triggers T0888
    /// recon detection (direction-independent per BC-2.14.020 EC-010).
    ///
    /// Traces to: BC-2.14.020 postcondition; F-105-003.
    #[test]
    fn test_BC_2_14_020_findings_contain_modbus_recon_T0888() {
        let json = run_modbus_json();
        let findings = json["findings"]
            .as_array()
            .expect("'findings' must be a JSON array");

        let has_recon = findings.iter().any(|f| {
            if let Some(techniques) = f["mitre_techniques"].as_array() {
                techniques.iter().any(|t| t.as_str() == Some("T0888"))
            } else {
                false
            }
        });

        assert!(
            has_recon,
            "No finding with T0888 found. FC=0x11 Report Server ID must emit T0888 recon. Findings: {:?}",
            findings
                .iter()
                .map(|f| &f["mitre_techniques"])
                .collect::<Vec<_>>()
        );
    }

    /// test_BC_2_14_020_recon_finding_count_two
    ///
    /// The fixture's FC=0x11 fires twice (once from client, once from server response)
    /// because BC-2.14.020 EC-010 specifies the recon detection is direction-independent.
    /// Both appearances must emit T0888 findings.
    ///
    /// Traces to: BC-2.14.020 EC-010; F-105-003.
    #[test]
    fn test_BC_2_14_020_recon_finding_count_two() {
        let json = run_modbus_json();
        let findings = json["findings"].as_array().expect("findings array");

        let recon_count = findings
            .iter()
            .filter(|f| {
                f["mitre_techniques"]
                    .as_array()
                    .map(|t| t.iter().any(|x| x.as_str() == Some("T0888")))
                    .unwrap_or(false)
            })
            .count();

        assert_eq!(
            recon_count, 2,
            "FC=0x11 fires in both directions; expected 2 T0888 findings, got {recon_count}"
        );
    }

    // ---------------------------------------------------------------------------
    // BC-2.09.007 / VP-021: timestamp provenance — not 1970
    // ---------------------------------------------------------------------------

    /// test_BC_2_09_007_finding_timestamps_have_correct_year
    ///
    /// Postcondition: every finding's `timestamp` field is a valid RFC3339 string
    /// with year 2024 (the fixture's packet timestamps are in Unix epoch 1717000000..
    /// = 2024-05-29). A 1970 timestamp would indicate the pipeline is using
    /// `timestamp = 0` (zero-epoch bug) rather than the pcap-relative capture time.
    ///
    /// Traces to: BC-2.09.007 postcondition 1; VP-021 timestamp provenance.
    #[test]
    fn test_BC_2_09_007_finding_timestamps_have_correct_year() {
        let json = run_modbus_json();
        let findings = json["findings"].as_array().expect("findings array");

        assert!(
            !findings.is_empty(),
            "findings must be non-empty to assert timestamp provenance"
        );

        for (i, finding) in findings.iter().enumerate() {
            let ts = finding["timestamp"]
                .as_str()
                .unwrap_or_else(|| panic!("finding[{i}].timestamp must be a string"));

            // RFC3339 timestamps from the fixture start with "2024-"
            // (Unix epoch 1717000000 ≈ 2024-05-29T16:26:40Z).
            assert!(
                ts.starts_with("2024-"),
                "finding[{i}].timestamp must be a 2024 RFC3339 date (pcap-relative provenance); \
                 got '{ts}' — a 1970 date indicates a timestamp-zero bug (VP-021 / BC-2.09.007)"
            );

            // Also verify it is parseable as RFC3339 (not a malformed string).
            ts.parse::<chrono::DateTime<chrono::Utc>>()
                .unwrap_or_else(|e| {
                    panic!("finding[{i}].timestamp '{ts}' is not valid RFC3339: {e}")
                });
        }
    }

    // ---------------------------------------------------------------------------
    // BC-2.14.023: --all flag also enables Modbus
    // ---------------------------------------------------------------------------

    /// test_BC_2_14_023_all_flag_also_enables_modbus_analyzer
    ///
    /// Postcondition: `wirerust analyze --all <fixture>` includes the "modbus" analyzer
    /// in its output, since `--all` implies `--modbus`.
    ///
    /// Traces to: BC-2.14.023 postcondition P1; F-105-003.
    #[test]
    fn test_BC_2_14_023_all_flag_also_enables_modbus_analyzer() {
        let output = Command::cargo_bin("wirerust")
            .expect("wirerust binary built")
            .args(["analyze", "--all", "--output-format", "json", FIXTURE])
            .assert()
            .success()
            .get_output()
            .stdout
            .clone();

        let text = String::from_utf8(output).expect("valid UTF-8");
        let json: serde_json::Value = serde_json::from_str(&text).expect("valid JSON");

        let analyzers = json["analyzers"].as_array().expect("analyzers array");
        let has_modbus = analyzers
            .iter()
            .any(|a| a["analyzer_name"].as_str() == Some("modbus"));

        assert!(
            has_modbus,
            "--all must enable the modbus analyzer; 'modbus' not found in analyzers: {:?}",
            analyzers
                .iter()
                .map(|a| &a["analyzer_name"])
                .collect::<Vec<_>>()
        );
    }
} // mod modbus_e2e
